export const MESSAGES = [
  {
    id: '1',
    name: 'Sandra',
    body: 'Sent you the pictures for the audition',
    date: new Date().toDateString(),
  },
  {
    id: '2',
    name: 'Me',
    body: 'Thanks for sending',
    date: new Date().toDateString(),
    isSender: true,
  },
  {
    id: '1',
    name: 'Sandra',
    body: 'Sent you the pictures for the audition',
    date: new Date().toDateString(),
  },
  {
    id: '2',
    name: 'Me',
    body: 'Thanks for sending',
    date: new Date().toDateString(),
    isSender: true,
  },
  {
    id: '1',
    name: 'Sandra',
    body: 'Sent you the pictures for the audition',
    date: new Date().toDateString(),
  },
  {
    id: '2',
    name: 'Me',
    body: 'Thanks for sending',
    date: new Date().toDateString(),
    isSender: true,
  },
  {
    id: '1',
    name: 'Sandra',
    body: 'Sent you the pictures for the audition',
    date: new Date().toDateString(),
  },
  {
    id: '2',
    name: 'Me',
    body: 'Thanks for sending',
    date: new Date().toDateString(),
    isSender: true,
  },
  {
    id: '1',
    name: 'Sandra',
    body: 'Sent you the pictures for the audition',
    date: new Date().toDateString(),
  },
  {
    id: '2',
    name: 'Me',
    body: 'Thanks for sending',
    date: new Date().toDateString(),
    isSender: true,
  },
  {
    id: '1',
    name: 'Sandra',
    body: 'Sent you the pictures for the audition',
    date: new Date().toDateString(),
  },
  {
    id: '2',
    name: 'Me',
    body: 'Thanks for sending',
    date: new Date().toDateString(),
    isSender: true,
  },
  {
    id: '1',
    name: 'Sandra',
    body: 'Sent you the pictures for the audition',
    date: new Date().toDateString(),
  },
  {
    id: '2',
    name: 'Me',
    body: 'Thanks for sending',
    date: new Date().toDateString(),
    isSender: true,
  },
];
